//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPT_KARPRO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime STARTDATE {
            get {
                return ((global::System.DateTime)(this["STARTDATE"]));
            }
            set {
                this["STARTDATE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime ENDDATE {
            get {
                return ((global::System.DateTime)(this["ENDDATE"]));
            }
            set {
                this["ENDDATE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=japer-server;uid=IT-JAPER;app=Microsoft® Visual Studio® 2015;wsid=SERVER-PC;d" +
            "atabase=JAPER-DATA")]
        public string JAPER_DATAConnectionString {
            get {
                return ((string)(this["JAPER_DATAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=ALDI;trusted_connection=Yes;app=Microsoft® Visual Studio® 2015;wsid=ALDI-PC;d" +
            "atabase=JAPER-DATA")]
        public string JAPER_DATAConnectionString1 {
            get {
                return ((string)(this["JAPER_DATAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=SERVER-PC;trusted_connection=Yes;app=Microsoft® Visual Studio® 2015;wsid=ALDI" +
            "-PC;database=JAPER-DATA")]
        public string JAPER_DATAConnectionString2 {
            get {
                return ((string)(this["JAPER_DATAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=SERVERPC;trusted_connection=Yes;app=Microsoft® Visual Studio® 2015;wsid=ALDI-" +
            "PC;database=JAPER-DATA1")]
        public string JAPER_DATA1ConnectionString {
            get {
                return ((string)(this["JAPER_DATA1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SUPREX\\SQLEXPRESS;Initial Catalog=JAPER-DATA;Integrated Security=True" +
            "")]
        public string bindingSource1 {
            get {
                return ((string)(this["bindingSource1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SUPREX\\SQLEXPRESS;Initial Catalog=BIO;Integrated Security=True")]
        public string BIOConnectionString {
            get {
                return ((string)(this["BIOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-4286IBB\\SQLEXPRESS;Initial Catalog=JAPER-DATA;Integrated Secu" +
            "rity=True")]
        public string JAPER_DATAConnectionString3 {
            get {
                return ((string)(this["JAPER_DATAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OVOPPT184\\SQLEXPRESS;Initial Catalog=JAPER-DATA;Integrated Security=T" +
            "rue")]
        public string JAPER_DATAConnectionString4 {
            get {
                return ((string)(this["JAPER_DATAConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=OVOPPT184\\SQLEXPRESS;Initial Catalog=JAPER-DATA;Persist Security Info" +
            "=True;User ID=japer;Password=japer1234")]
        public string JAPER_DATAConnectionString5 {
            get {
                return ((string)(this["JAPER_DATAConnectionString5"]));
            }
        }
    }
}
